contact_links:
  - name: Create an issue for dbt-core
    url: https://github.com/dbt-labs/dbt-core/issues/new/choose
    about: Report a bug or request a feature for dbt itself (not the Homebrew formula)
  - name: Ask a question or get support
    url: https://docs.getdbt.com/docs/guides/getting-help
    about: Ask a question or request support
