# TODO:
#   - test with `act -W .github/workflows/bottle.yml`
name: Build bottles for dbt formula

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: "The version number to release"
  #       required: true
  #     dbt-package:
  #       description: "Name of the dbt database adapter"
  #       required: true
  #     is-default-version:
  #       description: "Is this version the latest stable release?"
  #       required: false
  #       default: "false"
  # workflow_call:
  #   inputs:
  #     version:
  #       type: string
  #       description: "The version number to release"
  #       required: true
  #     dbt-package:
  #       type: string
  #       description: "Name of the dbt database adapter"
  #       required: true
  #     is-default-version:
  #       description: "Is this version the latest stable release?"
  #       type: boolean
  #       required: false
  #       default: false

env:
  # BUILD_DIR: ${{ github.workspace }}/build
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_CHANGE_ARCH_TO_ARM: 1

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu16.04:master
    outputs:
      runners: ${{steps.determine-runners.outputs.runners}}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Determine runners
        id: determine-runners
        run: brew determine-rebottle-runners "${{github.event.inputs.formula}}" "${{github.event.inputs.timeout}}"
