# **what?**
# This workflow installs the latest version of each dbt adapter from homebrew.
# It then runs 'dbt --version' to verify the installation was successful.
# If it fails for the scheduled runs, it will post to our team alerts channel.

# **why?**
# This is a simple way to test all adapter installations at a single
# time. It allows us to test them on a schedule as well to check for
# any breaking dependency changes that might happen and alert us on it.

# **when?**
# This workflow will run on a schedule every night and also can be
# manually invoked.

name: Homebrew installation testing

on:
  workflow_dispatch:

  # run this once per night to ensure no regressions
  schedule:
    - cron: "0 9,13,18 * * *" # 9:00, 13:00, 18:00 UTC

# no permissions are needed for this workflow
permissions: {}

jobs:
  homebrew:
    strategy:
      fail-fast: false
      matrix:
        adapter: ['dbt-postgres', 'dbt-redshift', 'dbt-snowflake', 'dbt-bigquery']
        os: [macos-11]

    runs-on: ${{ matrix.os }}

    steps:

      - name: "Prepare Brew"
        # brew upgrade generates some symlink update warnings that cause failures without the || true.
        # They're just that the symlink wasn't updated which is okay to ignore.
        # This does cause other errors to be ignored but for this case that's safe since the brew install
        # step would likely fail at that point.
        run: |
          brew update
          brew upgrade || true

      - name: "Check installed"
        run: brew list

      - name: "Brew Tap"
        run: |
          brew tap dbt-labs/dbt

      - name: "Brew install ${{ matrix.adapter }}"
        run: |
          brew install --verbose ${{ matrix.adapter }}

      - name: "Verify ${{ matrix.adapter }} version"
        run: |
          dbt --version

  post-failure:
    runs-on: ubuntu-latest
    needs: homebrew
    if: ${{ failure() }}

    steps:
      - name: Posting scheduled run failures
        uses: ravsamhq/notify-slack-action@v2
        if: ${{ github.event_name == 'schedule' }}
        with:
          notification_title: "Homebrew nightly integration test failed"
          status: ${{ job.status }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEV_CORE_ALERTS }}
