# **what?**
# This workflow installs the latest version of each dbt adapter from homebrew.
# It then run 'dbt --version' to verify the installation was successful. 
# If it fails for the scheduled runs, it will post to our team alerts channel.

# **why?**
# This is a simple way to test all adapter installations at a single
# time. It allows us to test them on a schedule as well to check for 
# any breaking dependency changes that might happen and alert us on it.

# **when?**
# This workflow will run on a schedule every night and also can be
# manually invoked.

name: Homebrew installation testing

on:
  workflow_dispatch:
  
  # run this once per night to ensure no regressions
  schedule:
    - cron: '0 5 * * *' # 5 UTC

# no permissions are needed for this workflow
permissions: {}

jobs:
  homebrew:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        adapter: ['dbt-postgres', 'dbt-redshift', 'dbt-snowflake', 'dbt-bigquery']

    steps:
      - name: Brew install ${{ matrix.adapter }}
        run: |
          brew update
          brew install git
          brew tap dbt-labs/dbt
          brew install ${{ matrix.adapter }}
          dbt --version
          
  post-failure:
    runs-on: ubuntu-latest
    needs: homebrew
    if: ${{ failure() }}

    steps:
      - name: Posting scheduled run failures
        uses: ravsamhq/notify-slack-action@v1
        if: ${{ github.event_name == 'schedule' }}
        with:
          notification_title: 'Homebrew nightly integration test failed'
          status: ${{ job.status }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEV_CORE_ALERTS }}
